apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    path: charts/demo-app
    repoURL: https://github.com/{{ .Values.repo.name }}
    targetRevision: {{ .Values.repo.revision }}
    helm:
      valuesObject:
        repo:
          name: {{ .Values.repo.name }}
          revision: {{ .Values.repo.revision }}
        service:
          nodePort: 30103
      valueFiles:
        - ../../gitops/dev/demo-app/values.yaml
      parameters:
        - name: commitID
          value: $ARGOCD_APP_REVISION
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
